name: "ðŸ“š Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs Every Day

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "ðŸ“¥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "ðŸ“š  Hashnode Updater"
        uses: "Sachin-chaurasiya/hashnode-blog-action@main"
        with:
          HASHNODE_PUBLICATION_NAME: "pratikkale.hashnode.dev"
          POST_COUNT: 6
          FORMAT: "stacked"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
